---
  - name: pacotes basicos
    apt: 
      name: "{{ packages }}"
      state: latest
      update_cache: yes

  - name: iniciar nginx
    service:
      name: nginx
      state: started
      enabled: yes

  - name: iniciar php e fpm
    service:
      name: php8.1-fpm
      state: started
      enabled: yes